[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]

padding = { x = 10, y = 25}
dynamic_padding = true
decorations = "Transparent"
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 13

[cursor]

style = { shape = "Beam", blinking = "on"}